version: '3'  
services:  
    sql-server:  
        image: mcr.microsoft.com/mssql/server:2017-latest 
        environment:  
            ACCEPT_EULA: 'Y'  
            SA_PASSWORD: 'TempPa55wd#'  
        ports: 
            - 1433:1433 